[meta]
name = "Craps Light"
author = "pxav"
version = "1.0"
description = "Simple light theme for craps"

[colors]
primary_background = "#ffffff"

primary_text = "#000000"
secondary_text = "#ffffff"

primary_button = "#326da8"
secondary_button = "#232b33"