[meta]
name = "Craps Dark"
author = "pxav"
version = "1.0"
description = "Simple dark theme for craps"

[colors]
primary_background = "#222222"

primary_text = "#ffffff"
secondary_text = "#ffffff"

primary_button = "#326da8"
secondary_button = "#232b33"